# Workflow to check for a recent OpenMM release candidate.
#
# If a recent RC is found, trigger a second workflow to test against it.
# See also: test-openmm-rc.yml
name: "Check for OpenMM RC"
on:
  schedule:
    - cron: "0 9 * * *"
  # use this for debugging
  #pull_request:
    #branch: master

jobs:
  check_rc:
    if: ${{ github.repository == 'openpathsampling/openpathsampling' }}
    runs-on: ubuntu-latest
    name: "Check for OpenMM RC"
    steps:
      - uses: actions/checkout@v2
      - uses: dwhswenson/conda-rc-check@v1
        id: checkrc
        with:
          channel: conda-forge
          package: openmm
          ndays: 3
          labels: openmm_rc
    outputs:
      hasrc: ${{ steps.checkrc.outputs.hasrc }}

  test_rc:
    needs: check_rc
    uses: ./.github/workflows/test-openmm-rc.yml
    secrets: inherit
    if: ${{ needs.check_rc.outputs.hasrc == 'True' }}
